// Seed set of common characters (roughly HSK1 level).
// Each entry: hanzi, pinyin (with tone marks), definition.
const SEED_HANZI = [
  ["我", "wǒ", "I; me"],
  ["你", "nǐ", "you"],
  ["他", "tā", "he; him"],
  ["她", "tā", "she; her"],
  ["是", "shì", "to be"],
  ["不", "bù", "not; no"],
  ["了", "le", "(completed action particle)"],
  ["人", "rén", "person"],
  ["在", "zài", "at; in; to exist"],
  ["有", "yǒu", "to have"],
  ["这", "zhè", "this"],
  ["那", "nà", "that"],
  ["都", "dōu", "all; both"],
  ["一", "yī", "one"],
  ["二", "èr", "two"],
  ["三", "sān", "three"],
  ["四", "sì", "four"],
  ["五", "wǔ", "five"],
  ["六", "liù", "six"],
  ["七", "qī", "seven"],
  ["八", "bā", "eight"],
  ["九", "jiǔ", "nine"],
  ["十", "shí", "ten"],
  ["大", "dà", "big"],
  ["小", "xiǎo", "small"],
  ["中", "zhōng", "middle; China"],
  ["国", "guó", "country"],
  ["学", "xué", "to study"],
  ["生", "shēng", "to be born; student"],
  ["老", "lǎo", "old"],
  ["师", "shī", "teacher"],
  ["朋", "péng", "friend"],
  ["友", "yǒu", "friend"],
  ["好", "hǎo", "good"],
  ["爱", "ài", "love"],
  ["家", "jiā", "family; home"],
  ["妈", "mā", "mom"],
  ["爸", "bà", "dad"],
  ["儿", "ér", "son; child"],
  ["子", "zi", "child; son (suffix)"],
  ["女", "nǚ", "woman; female"],
  ["男", "nán", "man; male"],
  ["天", "tiān", "day; sky"],
  ["年", "nián", "year"],
  ["月", "yuè", "month; moon"],
  ["日", "rì", "day; sun"],
  ["时", "shí", "time"],
  ["分", "fēn", "minute; to divide"],
  ["现", "xiàn", "now; present"],
  ["上", "shàng", "above; on"],
  ["下", "xià", "below; under"],
  ["去", "qù", "to go"],
  ["来", "lái", "to come"],
  ["吃", "chī", "to eat"],
  ["喝", "hē", "to drink"],
  ["水", "shuǐ", "water"],
  ["饭", "fàn", "rice; meal"],
  ["茶", "chá", "tea"],
  ["书", "shū", "book"],
  ["看", "kàn", "to look; to read"],
  ["说", "shuō", "to speak"],
  ["话", "huà", "word; speech"],
  ["听", "tīng", "to listen"],
  ["写", "xiě", "to write"],
  ["读", "dú", "to read"],
  ["走", "zǒu", "to walk"],
  ["跑", "pǎo", "to run"],
  ["坐", "zuò", "to sit"],
  ["站", "zhàn", "to stand; station"],
  ["门", "mén", "door"],
  ["车", "chē", "car; vehicle"],
  ["路", "lù", "road"],
  ["工", "gōng", "work"],
  ["作", "zuò", "to do; to make"],
  ["钱", "qián", "money"],
  ["买", "mǎi", "to buy"],
  ["卖", "mài", "to sell"],
  ["多", "duō", "many; much"],
  ["少", "shǎo", "few; little"],
  ["高", "gāo", "tall; high"],
  ["低", "dī", "low"],
  ["长", "cháng", "long"],
  ["短", "duǎn", "short"],
  ["新", "xīn", "new"],
  ["旧", "jiù", "old (things)"],
  ["快", "kuài", "fast"],
  ["慢", "màn", "slow"],
  ["早", "zǎo", "early"],
  ["晚", "wǎn", "late; evening"],
  ["今", "jīn", "now; present"],
  ["明", "míng", "bright; next"],
  ["昨", "zuó", "yesterday (prefix)"],
  ["心", "xīn", "heart"],
  ["手", "shǒu", "hand"],
  ["头", "tóu", "head"],
  ["眼", "yǎn", "eye"],
  ["口", "kǒu", "mouth"],
  ["火", "huǒ", "fire"],
  ["山", "shān", "mountain"],
];
