// Seed set of common characters and words.
// Each entry: hanzi, pinyin (with tone marks), definition, level.
//
// "level" is a rough, hand-picked grouping (not verified against the
// official HSK word list) — good enough for organizing a starter deck,
// not a substitute for an authoritative HSK wordlist. Import a real one
// via the Browse view if you need exact official coverage.
const SEED_HANZI = [
  // ---- HSK1-ish: single characters, the basics ----
  ["我", "wǒ", "I; me", "HSK1"],
  ["你", "nǐ", "you", "HSK1"],
  ["他", "tā", "he; him", "HSK1"],
  ["她", "tā", "she; her", "HSK1"],
  ["是", "shì", "to be", "HSK1"],
  ["不", "bù", "not; no", "HSK1"],
  ["了", "le", "(completed action particle)", "HSK1"],
  ["人", "rén", "person", "HSK1"],
  ["在", "zài", "at; in; to exist", "HSK1"],
  ["有", "yǒu", "to have", "HSK1"],
  ["这", "zhè", "this", "HSK1"],
  ["那", "nà", "that", "HSK1"],
  ["都", "dōu", "all; both", "HSK1"],
  ["一", "yī", "one", "HSK1"],
  ["二", "èr", "two", "HSK1"],
  ["三", "sān", "three", "HSK1"],
  ["四", "sì", "four", "HSK1"],
  ["五", "wǔ", "five", "HSK1"],
  ["六", "liù", "six", "HSK1"],
  ["七", "qī", "seven", "HSK1"],
  ["八", "bā", "eight", "HSK1"],
  ["九", "jiǔ", "nine", "HSK1"],
  ["十", "shí", "ten", "HSK1"],
  ["大", "dà", "big", "HSK1"],
  ["小", "xiǎo", "small", "HSK1"],
  ["中", "zhōng", "middle; China", "HSK1"],
  ["国", "guó", "country", "HSK1"],
  ["学", "xué", "to study", "HSK1"],
  ["生", "shēng", "to be born; student", "HSK1"],
  ["老", "lǎo", "old", "HSK1"],
  ["师", "shī", "teacher", "HSK1"],
  ["朋", "péng", "friend", "HSK1"],
  ["友", "yǒu", "friend", "HSK1"],
  ["好", "hǎo", "good", "HSK1"],
  ["爱", "ài", "love", "HSK1"],
  ["家", "jiā", "family; home", "HSK1"],
  ["妈", "mā", "mom", "HSK1"],
  ["爸", "bà", "dad", "HSK1"],
  ["儿", "ér", "son; child", "HSK1"],
  ["子", "zi", "child; son (suffix)", "HSK1"],
  ["女", "nǚ", "woman; female", "HSK1"],
  ["男", "nán", "man; male", "HSK1"],
  ["天", "tiān", "day; sky", "HSK1"],
  ["年", "nián", "year", "HSK1"],
  ["月", "yuè", "month; moon", "HSK1"],
  ["日", "rì", "day; sun", "HSK1"],
  ["时", "shí", "time", "HSK1"],
  ["分", "fēn", "minute; to divide", "HSK1"],
  ["现", "xiàn", "now; present", "HSK1"],
  ["上", "shàng", "above; on", "HSK1"],
  ["下", "xià", "below; under", "HSK1"],
  ["去", "qù", "to go", "HSK1"],
  ["来", "lái", "to come", "HSK1"],
  ["吃", "chī", "to eat", "HSK1"],
  ["喝", "hē", "to drink", "HSK1"],
  ["水", "shuǐ", "water", "HSK1"],
  ["饭", "fàn", "rice; meal", "HSK1"],
  ["茶", "chá", "tea", "HSK1"],
  ["书", "shū", "book", "HSK1"],
  ["看", "kàn", "to look; to read", "HSK1"],
  ["说", "shuō", "to speak", "HSK1"],
  ["话", "huà", "word; speech", "HSK1"],
  ["听", "tīng", "to listen", "HSK1"],
  ["写", "xiě", "to write", "HSK1"],
  ["读", "dú", "to read", "HSK1"],
  ["走", "zǒu", "to walk", "HSK1"],
  ["跑", "pǎo", "to run", "HSK1"],
  ["坐", "zuò", "to sit", "HSK1"],
  ["站", "zhàn", "to stand; station", "HSK1"],
  ["门", "mén", "door", "HSK1"],
  ["车", "chē", "car; vehicle", "HSK1"],
  ["路", "lù", "road", "HSK1"],
  ["工", "gōng", "work", "HSK1"],
  ["作", "zuò", "to do; to make", "HSK1"],
  ["钱", "qián", "money", "HSK1"],
  ["买", "mǎi", "to buy", "HSK1"],
  ["卖", "mài", "to sell", "HSK1"],
  ["多", "duō", "many; much", "HSK1"],
  ["少", "shǎo", "few; little", "HSK1"],
  ["高", "gāo", "tall; high", "HSK1"],
  ["低", "dī", "low", "HSK1"],
  ["长", "cháng", "long", "HSK1"],
  ["短", "duǎn", "short", "HSK1"],
  ["新", "xīn", "new", "HSK1"],
  ["旧", "jiù", "old (things)", "HSK1"],
  ["快", "kuài", "fast", "HSK1"],
  ["慢", "màn", "slow", "HSK1"],
  ["早", "zǎo", "early", "HSK1"],
  ["晚", "wǎn", "late; evening", "HSK1"],
  ["今", "jīn", "now; present", "HSK1"],
  ["明", "míng", "bright; next", "HSK1"],
  ["昨", "zuó", "yesterday (prefix)", "HSK1"],
  ["心", "xīn", "heart", "HSK1"],
  ["手", "shǒu", "hand", "HSK1"],
  ["头", "tóu", "head", "HSK1"],
  ["眼", "yǎn", "eye", "HSK1"],
  ["口", "kǒu", "mouth", "HSK1"],
  ["火", "huǒ", "fire", "HSK1"],
  ["山", "shān", "mountain", "HSK1"],

  // ---- HSK2+ ish: common two-character words ----
  ["想", "xiǎng", "to think; to want", "HSK2+"],
  ["可以", "kěyǐ", "can; may", "HSK2+"],
  ["应该", "yīnggāi", "should", "HSK2+"],
  ["因为", "yīnwèi", "because", "HSK2+"],
  ["所以", "suǒyǐ", "so; therefore", "HSK2+"],
  ["但是", "dànshì", "but", "HSK2+"],
  ["如果", "rúguǒ", "if", "HSK2+"],
  ["虽然", "suīrán", "although", "HSK2+"],
  ["已经", "yǐjīng", "already", "HSK2+"],
  ["还", "hái", "still; also", "HSK2+"],
  ["再", "zài", "again", "HSK2+"],
  ["就", "jiù", "then; just", "HSK2+"],
  ["才", "cái", "only then", "HSK2+"],
  ["也", "yě", "also", "HSK2+"],
  ["很", "hěn", "very", "HSK2+"],
  ["非常", "fēicháng", "extremely", "HSK2+"],
  ["特别", "tèbié", "especially", "HSK2+"],
  ["一起", "yìqǐ", "together", "HSK2+"],
  ["一样", "yíyàng", "the same", "HSK2+"],
  ["不同", "bùtóng", "different", "HSK2+"],
  ["东西", "dōngxi", "thing", "HSK2+"],
  ["事情", "shìqing", "matter; affair", "HSK2+"],
  ["问题", "wèntí", "problem; question", "HSK2+"],
  ["办法", "bànfǎ", "method; way", "HSK2+"],
  ["关系", "guānxi", "relationship", "HSK2+"],
  ["机会", "jīhuì", "opportunity", "HSK2+"],
  ["经验", "jīngyàn", "experience", "HSK2+"],
  ["历史", "lìshǐ", "history", "HSK2+"],
  ["文化", "wénhuà", "culture", "HSK2+"],
  ["音乐", "yīnyuè", "music", "HSK2+"],
  ["电影", "diànyǐng", "movie", "HSK2+"],
  ["电视", "diànshì", "television", "HSK2+"],
  ["电脑", "diànnǎo", "computer", "HSK2+"],
  ["手机", "shǒujī", "mobile phone", "HSK2+"],
  ["银行", "yínháng", "bank", "HSK2+"],
  ["医院", "yīyuàn", "hospital", "HSK2+"],
  ["学校", "xuéxiào", "school", "HSK2+"],
  ["公司", "gōngsī", "company", "HSK2+"],
  ["商店", "shāngdiàn", "store; shop", "HSK2+"],
  ["超市", "chāoshì", "supermarket", "HSK2+"],
  ["机场", "jīchǎng", "airport", "HSK2+"],
  ["火车", "huǒchē", "train", "HSK2+"],
  ["飞机", "fēijī", "airplane", "HSK2+"],
  ["地铁", "dìtiě", "subway", "HSK2+"],
  ["天气", "tiānqì", "weather", "HSK2+"],
  ["晴", "qíng", "sunny; clear", "HSK2+"],
  ["阴", "yīn", "cloudy; overcast", "HSK2+"],
  ["雪", "xuě", "snow", "HSK2+"],
  ["风", "fēng", "wind", "HSK2+"],
  ["冷", "lěng", "cold", "HSK2+"],
  ["热", "rè", "hot", "HSK2+"],
  ["春", "chūn", "spring", "HSK2+"],
  ["夏", "xià", "summer", "HSK2+"],
  ["秋", "qiū", "autumn", "HSK2+"],
  ["冬", "dōng", "winter", "HSK2+"],
  ["城市", "chéngshì", "city", "HSK2+"],
  ["国家", "guójiā", "country; nation", "HSK2+"],
  ["世界", "shìjiè", "world", "HSK2+"],
  ["地方", "dìfang", "place", "HSK2+"],
  ["东", "dōng", "east", "HSK2+"],
  ["西", "xī", "west", "HSK2+"],
  ["南", "nán", "south", "HSK2+"],
  ["北", "běi", "north", "HSK2+"],
  ["前面", "qiánmiàn", "in front; front", "HSK2+"],
  ["后面", "hòumiàn", "behind; back", "HSK2+"],
  ["里面", "lǐmiàn", "inside", "HSK2+"],
  ["外面", "wàimiàn", "outside", "HSK2+"],
  ["旁边", "pángbiān", "next to; beside", "HSK2+"],
  ["中间", "zhōngjiān", "middle; between", "HSK2+"],
  ["附近", "fùjìn", "nearby", "HSK2+"],
  ["颜色", "yánsè", "color", "HSK2+"],
  ["红", "hóng", "red", "HSK2+"],
  ["黄", "huáng", "yellow", "HSK2+"],
  ["蓝", "lán", "blue", "HSK2+"],
  ["绿", "lǜ", "green", "HSK2+"],
  ["黑", "hēi", "black", "HSK2+"],
  ["白", "bái", "white", "HSK2+"],
  ["穿", "chuān", "to wear", "HSK2+"],
  ["衣服", "yīfu", "clothes", "HSK2+"],
  ["裤子", "kùzi", "pants", "HSK2+"],
  ["鞋", "xié", "shoes", "HSK2+"],
  ["睡觉", "shuìjiào", "to sleep", "HSK2+"],
  ["起床", "qǐchuáng", "to get up", "HSK2+"],
  ["洗澡", "xǐzǎo", "to bathe", "HSK2+"],
  ["运动", "yùndòng", "exercise; sports", "HSK2+"],
  ["游泳", "yóuyǒng", "to swim", "HSK2+"],
  ["篮球", "lánqiú", "basketball", "HSK2+"],
  ["足球", "zúqiú", "soccer", "HSK2+"],
  ["唱歌", "chànggē", "to sing", "HSK2+"],
  ["跳舞", "tiàowǔ", "to dance", "HSK2+"],
  ["旅游", "lǚyóu", "to travel", "HSK2+"],
  ["照相", "zhàoxiàng", "to take a photo", "HSK2+"],
  ["帮助", "bāngzhù", "to help", "HSK2+"],
  ["喜欢", "xǐhuan", "to like", "HSK2+"],
  ["希望", "xīwàng", "to hope", "HSK2+"],
  ["觉得", "juéde", "to feel; to think", "HSK2+"],
  ["知道", "zhīdào", "to know", "HSK2+"],
  ["认识", "rènshi", "to know (a person); to recognize", "HSK2+"],
  ["明白", "míngbai", "to understand", "HSK2+"],
  ["懂", "dǒng", "to understand", "HSK2+"],
  ["忘记", "wàngjì", "to forget", "HSK2+"],
  ["记得", "jìde", "to remember", "HSK2+"],

  // ---- Geography: countries, cities, continents ----
  ["中国", "Zhōngguó", "China", "Geography"],
  ["美国", "Měiguó", "United States", "Geography"],
  ["英国", "Yīngguó", "United Kingdom", "Geography"],
  ["法国", "Fàguó", "France", "Geography"],
  ["德国", "Déguó", "Germany", "Geography"],
  ["日本", "Rìběn", "Japan", "Geography"],
  ["韩国", "Hánguó", "South Korea", "Geography"],
  ["俄罗斯", "Éluósī", "Russia", "Geography"],
  ["加拿大", "Jiānádà", "Canada", "Geography"],
  ["澳大利亚", "Àodàlìyà", "Australia", "Geography"],
  ["意大利", "Yìdàlì", "Italy", "Geography"],
  ["西班牙", "Xībānyá", "Spain", "Geography"],
  ["印度", "Yìndù", "India", "Geography"],
  ["巴西", "Bāxī", "Brazil", "Geography"],
  ["墨西哥", "Mòxīgē", "Mexico", "Geography"],
  ["埃及", "Āijí", "Egypt", "Geography"],
  ["泰国", "Tàiguó", "Thailand", "Geography"],
  ["越南", "Yuènán", "Vietnam", "Geography"],
  ["新加坡", "Xīnjiāpō", "Singapore", "Geography"],
  ["瑞士", "Ruìshì", "Switzerland", "Geography"],
  ["北京", "Běijīng", "Beijing", "Geography"],
  ["上海", "Shànghǎi", "Shanghai", "Geography"],
  ["广州", "Guǎngzhōu", "Guangzhou", "Geography"],
  ["深圳", "Shēnzhèn", "Shenzhen", "Geography"],
  ["香港", "Xiānggǎng", "Hong Kong", "Geography"],
  ["台北", "Táiběi", "Taipei", "Geography"],
  ["纽约", "Niǔyuē", "New York", "Geography"],
  ["伦敦", "Lúndūn", "London", "Geography"],
  ["巴黎", "Bālí", "Paris", "Geography"],
  ["东京", "Dōngjīng", "Tokyo", "Geography"],
  ["首尔", "Shǒu'ěr", "Seoul", "Geography"],
  ["悉尼", "Xīní", "Sydney", "Geography"],
  ["莫斯科", "Mòsīkē", "Moscow", "Geography"],
  ["亚洲", "Yàzhōu", "Asia", "Geography"],
  ["欧洲", "Ōuzhōu", "Europe", "Geography"],
  ["非洲", "Fēizhōu", "Africa", "Geography"],
  ["北美洲", "Běiměizhōu", "North America", "Geography"],
  ["南美洲", "Nánměizhōu", "South America", "Geography"],
  ["大洋洲", "Dàyángzhōu", "Oceania", "Geography"],

  // ---- Common four-character idioms (成语) ----
  // Definitions give the figurative meaning; literal image noted where it helps.
  ["马马虎虎", "mǎmǎhūhū", "careless; so-so", "Idiom"],
  ["半途而废", "bàntú'érfèi", "to give up halfway", "Idiom"],
  ["画蛇添足", "huàshétiānzú", "to ruin by overdoing it (lit. draw a snake, add feet)", "Idiom"],
  ["守株待兔", "shǒuzhūdàitù", "to wait idly for a windfall (lit. guard a stump, wait for a rabbit)", "Idiom"],
  ["一举两得", "yìjǔliǎngdé", "to kill two birds with one stone", "Idiom"],
  ["入乡随俗", "rùxiāngsuísú", "when in Rome, do as the Romans do", "Idiom"],
  ["狼吞虎咽", "lángtūnhǔyàn", "to wolf down food", "Idiom"],
  ["对牛弹琴", "duìniútánqín", "to waste words on the wrong audience (lit. play lute to a cow)", "Idiom"],
  ["自相矛盾", "zìxiāngmáodùn", "self-contradictory", "Idiom"],
  ["画龙点睛", "huàlóngdiǎnjīng", "to add the crucial finishing touch", "Idiom"],
  ["亡羊补牢", "wángyángbǔláo", "better late than never (lit. mend the pen after the sheep is lost)", "Idiom"],
  ["拔苗助长", "bámiáozhùzhǎng", "to ruin things by forcing progress", "Idiom"],
  ["井底之蛙", "jǐngdǐzhīwā", "a person with a narrow view (lit. frog at the bottom of a well)", "Idiom"],
  ["掩耳盗铃", "yǎn'ěrdàolíng", "to deceive only oneself", "Idiom"],
  ["刻舟求剑", "kèzhōuqiújiàn", "rigidly stuck to an outdated method", "Idiom"],
  ["塞翁失马", "sàiwēngshīmǎ", "a blessing in disguise", "Idiom"],
  ["胸有成竹", "xiōngyǒuchéngzhú", "to have a well-thought-out plan already in mind", "Idiom"],
  ["纸上谈兵", "zhǐshàngtánbīng", "armchair strategy; all theory, no practice", "Idiom"],
  ["锦上添花", "jǐnshàngtiānhuā", "to make something already good even better", "Idiom"],
  ["雪中送炭", "xuězhōngsòngtàn", "to help someone in urgent need", "Idiom"],
  ["一心一意", "yìxīnyíyì", "wholeheartedly", "Idiom"],
  ["半信半疑", "bànxìnbànyí", "half-believing, half-doubting", "Idiom"],
  ["恍然大悟", "huǎngrándàwù", "to suddenly realize", "Idiom"],
  ["不可思议", "bùkěsīyì", "inconceivable; unimaginable", "Idiom"],
  ["心想事成", "xīnxiǎngshìchéng", "may your wishes come true", "Idiom"],
  ["一帆风顺", "yìfānfēngshùn", "smooth sailing", "Idiom"],
  ["万事如意", "wànshìrúyì", "may everything go as you wish", "Idiom"],
  ["人山人海", "rénshānrénhǎi", "a huge crowd (lit. people mountain, people sea)", "Idiom"],
  ["乱七八糟", "luànqībāzāo", "in a total mess", "Idiom"],
  ["知足常乐", "zhīzúchánglè", "content with what one has is always happy", "Idiom"],
];
