// Vocabulary deck.
// Each entry: hanzi, pinyin (with tone marks), definition, level.
//
// HSK1/HSK2/HSK3 word choice and level assignment are sourced from the
// official 2012-standard HSK word lists (via the CC-CEDICT-derived
// drkameleon/complete-hsk-vocabulary dataset), not hand-picked — the
// hanzi/pinyin/level triples are grounded in that source. Single-character
// entries had their pinyin reading and primary meaning manually reviewed
// and corrected where the source's automatic reading-selection picked an
// obscure or wrong pronunciation for a polyphonic character (a real risk
// with dictionary data — e.g. 个/和/看/万/云 all needed correction).
//
// "HSK1 (extra)" and "HSK4+ (extra)" are words that don't appear in the
// official HSK1-3 lists at all — kept because they're common/useful, but
// explicitly separated so the level tag doesn't overclaim official status.
// Geography and Idiom entries are hand-picked (see their own notes below)
// and not part of the HSK standard.
const SEED_HANZI = [
  // ---- HSK1 (official 2012-standard word list, 150 words) ----
  ["我", "wǒ", "I; me", "HSK1"],
  ["你", "nǐ", "you", "HSK1"],
  ["他", "tā", "he; him", "HSK1"],
  ["她", "tā", "she; her", "HSK1"],
  ["是", "shì", "to be", "HSK1"],
  ["不", "bù", "not; no", "HSK1"],
  ["了", "le", "(completed action particle)", "HSK1"],
  ["人", "rén", "person", "HSK1"],
  ["在", "zài", "at; in; to exist", "HSK1"],
  ["有", "yǒu", "to have", "HSK1"],
  ["这", "zhè", "this", "HSK1"],
  ["那", "nà", "that", "HSK1"],
  ["都", "dōu", "all; both", "HSK1"],
  ["一", "yī", "one", "HSK1"],
  ["二", "èr", "two", "HSK1"],
  ["三", "sān", "three", "HSK1"],
  ["四", "sì", "four", "HSK1"],
  ["五", "wǔ", "five", "HSK1"],
  ["六", "liù", "six", "HSK1"],
  ["七", "qī", "seven", "HSK1"],
  ["八", "bā", "eight", "HSK1"],
  ["九", "jiǔ", "nine", "HSK1"],
  ["十", "shí", "ten", "HSK1"],
  ["大", "dà", "big", "HSK1"],
  ["小", "xiǎo", "small", "HSK1"],
  ["好", "hǎo", "good", "HSK1"],
  ["爱", "ài", "love", "HSK1"],
  ["家", "jiā", "family; home", "HSK1"],
  ["年", "nián", "year", "HSK1"],
  ["月", "yuè", "month; moon", "HSK1"],
  ["日", "rì", "day; sun", "HSK1"],
  ["上", "shàng", "above; on", "HSK1"],
  ["下", "xià", "below; under", "HSK1"],
  ["去", "qù", "to go", "HSK1"],
  ["来", "lái", "to come", "HSK1"],
  ["吃", "chī", "to eat", "HSK1"],
  ["喝", "hē", "to drink", "HSK1"],
  ["水", "shuǐ", "water", "HSK1"],
  ["茶", "chá", "tea", "HSK1"],
  ["书", "shū", "book", "HSK1"],
  ["看", "kàn", "to look; to read", "HSK1"],
  ["听", "tīng", "to listen", "HSK1"],
  ["写", "xiě", "to write", "HSK1"],
  ["读", "dú", "to read", "HSK1"],
  ["坐", "zuò", "to sit", "HSK1"],
  ["钱", "qián", "money", "HSK1"],
  ["买", "mǎi", "to buy", "HSK1"],
  ["多", "duō", "many; much", "HSK1"],
  ["少", "shǎo", "few; little", "HSK1"],
  ["想", "xiǎng", "to think; to want", "HSK1"],
  ["很", "hěn", "very", "HSK1"],
  ["东西", "dōngxi", "thing", "HSK1"],
  ["电影", "diànyǐng", "movie", "HSK1"],
  ["电视", "diànshì", "television", "HSK1"],
  ["电脑", "diànnǎo", "computer", "HSK1"],
  ["医院", "yīyuàn", "hospital", "HSK1"],
  ["学校", "xuéxiào", "school", "HSK1"],
  ["商店", "shāngdiàn", "store; shop", "HSK1"],
  ["飞机", "fēijī", "airplane", "HSK1"],
  ["天气", "tiānqì", "weather", "HSK1"],
  ["冷", "lěng", "cold", "HSK1"],
  ["热", "rè", "hot", "HSK1"],
  ["前面", "qiánmiàn", "in front; front", "HSK1"],
  ["后面", "hòumiàn", "behind; back", "HSK1"],
  ["衣服", "yīfu", "clothes", "HSK1"],
  ["睡觉", "shuìjiào", "to sleep", "HSK1"],
  ["喜欢", "xǐhuan", "to like", "HSK1"],
  ["认识", "rènshi", "to know (a person); to recognize", "HSK1"],
  ["爸爸", "bàba", "(coll.) father; dad", "HSK1"],
  ["杯子", "bēizi", "cup; glass", "HSK1"],
  ["本", "běn", "(measure word for books); this; the current", "HSK1"],
  ["不客气", "bùkèqi", "you're welcome; don't mention it", "HSK1"],
  ["菜", "cài", "vegetable; dish", "HSK1"],
  ["出租车", "chūzūchē", "taxi", "HSK1"],
  ["打电话", "dǎdiànhuà", "to make a telephone call", "HSK1"],
  ["的", "de", "(possessive particle)", "HSK1"],
  ["点", "diǎn", "point; o'clock; a little", "HSK1"],
  ["对不起", "duìbuqǐ", "sorry; excuse me", "HSK1"],
  ["多少", "duōshao", "how much; how many", "HSK1"],
  ["儿子", "érzi", "son", "HSK1"],
  ["饭馆", "fànguǎn", "restaurant", "HSK1"],
  ["分钟", "fēnzhōng", "minute", "HSK1"],
  ["高兴", "gāoxìng", "happy; glad", "HSK1"],
  ["个", "gè", "(general measure word)", "HSK1"],
  ["工作", "gōngzuò", "to work; (of a machine) to operate", "HSK1"],
  ["狗", "gǒu", "dog", "HSK1"],
  ["汉语", "Hànyǔ", "Chinese language", "HSK1"],
  ["和", "hé", "and; with", "HSK1"],
  ["回", "huí", "to return; (measure word for occurrences)", "HSK1"],
  ["会", "huì", "can; to be able to; meeting", "HSK1"],
  ["火车站", "huǒchēzhàn", "train station", "HSK1"],
  ["几", "jǐ", "how many; several", "HSK1"],
  ["叫", "jiào", "to be called; to shout", "HSK1"],
  ["今天", "jīntiān", "today; at the present", "HSK1"],
  ["开", "kāi", "to open; to turn on; to drive", "HSK1"],
  ["看见", "kànjiàn", "to see; to catch sight of", "HSK1"],
  ["块", "kuài", "piece; lump; (measure word for money, colloquial for yuan)", "HSK1"],
  ["老师", "lǎoshī", "teacher", "HSK1"],
  ["里", "lǐ", "inside; in", "HSK1"],
  ["零", "líng", "zero", "HSK1"],
  ["妈妈", "māma", "mama; mommy", "HSK1"],
  ["吗", "ma", "(question particle)", "HSK1"],
  ["猫", "māo", "cat", "HSK1"],
  ["没", "méi", "not; have not", "HSK1"],
  ["没关系", "méiguānxi", "it doesn't matter", "HSK1"],
  ["米饭", "mǐfàn", "(cooked) rice", "HSK1"],
  ["名字", "míngzi", "name (of a person or thing)", "HSK1"],
  ["明天", "míngtiān", "tomorrow", "HSK1"],
  ["哪", "nǎ", "which", "HSK1"],
  ["呢", "ne", "(question particle)", "HSK1"],
  ["能", "néng", "can; to be able to", "HSK1"],
  ["女儿", "nǚér", "daughter", "HSK1"],
  ["朋友", "péngyou", "friend", "HSK1"],
  ["漂亮", "piàoliang", "pretty; beautiful", "HSK1"],
  ["苹果", "píngguǒ", "apple", "HSK1"],
  ["请", "qǐng", "please; to invite", "HSK1"],
  ["上午", "shàngwǔ", "morning", "HSK1"],
  ["什么", "shénme", "what?; something", "HSK1"],
  ["时候", "shíhou", "time; length of time", "HSK1"],
  ["谁", "shéi", "who", "HSK1"],
  ["水果", "shuǐguǒ", "fruit", "HSK1"],
  ["说话", "shuōhuà", "to speak; to say", "HSK1"],
  ["岁", "suì", "year (of age); years old", "HSK1"],
  ["太", "tài", "too; very", "HSK1"],
  ["同学", "tóngxué", "to study at the same school; fellow student", "HSK1"],
  ["喂", "wéi", "hello (when answering the phone); hey", "HSK1"],
  ["我们", "wǒmen", "we; us", "HSK1"],
  ["下午", "xiàwǔ", "afternoon; p.m.", "HSK1"],
  ["下雨", "xiàyǔ", "to rain", "HSK1"],
  ["先生", "xiānsheng", "teacher; gentleman; sir; mister (Mr.)", "HSK1"],
  ["现在", "xiànzài", "now; at present", "HSK1"],
  ["小姐", "xiǎojie", "young lady; miss", "HSK1"],
  ["些", "xiē", "some; a few", "HSK1"],
  ["谢谢", "xièxie", "to thank; thanks", "HSK1"],
  ["星期", "xīngqī", "week; day of the week", "HSK1"],
  ["学生", "xuésheng", "student; schoolchild", "HSK1"],
  ["学习", "xuéxí", "to learn; to study", "HSK1"],
  ["医生", "yīshēng", "doctor", "HSK1"],
  ["椅子", "yǐzi", "chair", "HSK1"],
  ["再见", "zàijiàn", "goodbye; see you again later", "HSK1"],
  ["怎么", "zěnme", "how?; what?", "HSK1"],
  ["怎么样", "zěnmeyàng", "how?; how about?", "HSK1"],
  ["中午", "zhōngwǔ", "noon; midday", "HSK1"],
  ["住", "zhù", "to live; to reside", "HSK1"],
  ["桌子", "zhuōzi", "table; desk", "HSK1"],
  ["字", "zì", "character; word", "HSK1"],
  ["昨天", "zuótiān", "yesterday", "HSK1"],
  ["做", "zuò", "to do; to make", "HSK1"],

  // ---- HSK1-adjacent basics not in the official word list (common but not exam-verified) ----
  ["中", "zhōng", "middle; China", "HSK1 (extra)"],
  ["国", "guó", "country", "HSK1 (extra)"],
  ["学", "xué", "to study", "HSK1 (extra)"],
  ["生", "shēng", "to be born; student", "HSK1 (extra)"],
  ["师", "shī", "teacher", "HSK1 (extra)"],
  ["朋", "péng", "friend", "HSK1 (extra)"],
  ["友", "yǒu", "friend", "HSK1 (extra)"],
  ["妈", "mā", "mom", "HSK1 (extra)"],
  ["爸", "bà", "dad", "HSK1 (extra)"],
  ["儿", "ér", "son; child", "HSK1 (extra)"],
  ["子", "zi", "child; son (suffix)", "HSK1 (extra)"],
  ["女", "nǚ", "woman; female", "HSK1 (extra)"],
  ["男", "nán", "man; male", "HSK1 (extra)"],
  ["天", "tiān", "day; sky", "HSK1 (extra)"],
  ["时", "shí", "time", "HSK1 (extra)"],
  ["现", "xiàn", "now; present", "HSK1 (extra)"],
  ["饭", "fàn", "rice; meal", "HSK1 (extra)"],
  ["说", "shuō", "to speak", "HSK1 (extra)"],
  ["话", "huà", "word; speech", "HSK1 (extra)"],
  ["跑", "pǎo", "to run", "HSK1 (extra)"],
  ["车", "chē", "car; vehicle", "HSK1 (extra)"],
  ["工", "gōng", "work", "HSK1 (extra)"],
  ["作", "zuò", "to do; to make", "HSK1 (extra)"],
  ["早", "zǎo", "early", "HSK1 (extra)"],
  ["晚", "wǎn", "late; evening", "HSK1 (extra)"],
  ["今", "jīn", "now; present", "HSK1 (extra)"],
  ["明", "míng", "bright; next", "HSK1 (extra)"],
  ["昨", "zuó", "yesterday (prefix)", "HSK1 (extra)"],
  ["心", "xīn", "heart", "HSK1 (extra)"],
  ["手", "shǒu", "hand", "HSK1 (extra)"],
  ["头", "tóu", "head", "HSK1 (extra)"],
  ["眼", "yǎn", "eye", "HSK1 (extra)"],
  ["火", "huǒ", "fire", "HSK1 (extra)"],
  ["山", "shān", "mountain", "HSK1 (extra)"],

  // ---- HSK2 (official 2012-standard word list, 150 words) ----
  ["走", "zǒu", "to walk", "HSK2"],
  ["门", "mén", "door", "HSK2"],
  ["路", "lù", "road", "HSK2"],
  ["卖", "mài", "to sell", "HSK2"],
  ["高", "gāo", "tall; high", "HSK2"],
  ["长", "cháng", "long", "HSK2"],
  ["新", "xīn", "new", "HSK2"],
  ["快", "kuài", "fast", "HSK2"],
  ["慢", "màn", "slow", "HSK2"],
  ["可以", "kěyǐ", "can; may", "HSK2"],
  ["因为", "yīnwèi", "because", "HSK2"],
  ["所以", "suǒyǐ", "so; therefore", "HSK2"],
  ["但是", "dànshì", "but", "HSK2"],
  ["已经", "yǐjīng", "already", "HSK2"],
  ["还", "hái", "still; also", "HSK2"],
  ["再", "zài", "again", "HSK2"],
  ["就", "jiù", "then; just", "HSK2"],
  ["也", "yě", "also", "HSK2"],
  ["非常", "fēicháng", "extremely", "HSK2"],
  ["一起", "yìqǐ", "together", "HSK2"],
  ["事情", "shìqing", "matter; affair", "HSK2"],
  ["问题", "wèntí", "problem; question", "HSK2"],
  ["手机", "shǒujī", "mobile phone", "HSK2"],
  ["公司", "gōngsī", "company", "HSK2"],
  ["机场", "jīchǎng", "airport", "HSK2"],
  ["晴", "qíng", "sunny; clear", "HSK2"],
  ["阴", "yīn", "cloudy; overcast", "HSK2"],
  ["雪", "xuě", "snow", "HSK2"],
  ["旁边", "pángbiān", "next to; beside", "HSK2"],
  ["颜色", "yánsè", "color", "HSK2"],
  ["红", "hóng", "red", "HSK2"],
  ["黑", "hēi", "black", "HSK2"],
  ["白", "bái", "white", "HSK2"],
  ["穿", "chuān", "to wear", "HSK2"],
  ["起床", "qǐchuáng", "to get up", "HSK2"],
  ["运动", "yùndòng", "exercise; sports", "HSK2"],
  ["游泳", "yóuyǒng", "to swim", "HSK2"],
  ["唱歌", "chànggē", "to sing", "HSK2"],
  ["跳舞", "tiàowǔ", "to dance", "HSK2"],
  ["旅游", "lǚyóu", "to travel", "HSK2"],
  ["帮助", "bāngzhù", "to help", "HSK2"],
  ["希望", "xīwàng", "to hope", "HSK2"],
  ["觉得", "juéde", "to feel; to think", "HSK2"],
  ["知道", "zhīdào", "to know", "HSK2"],
  ["懂", "dǒng", "to understand", "HSK2"],
  ["吧", "ba", "(suggestion or assumption particle)", "HSK2"],
  ["百", "bǎi", "hundred", "HSK2"],
  ["报纸", "bàozhǐ", "newspaper; newsprint", "HSK2"],
  ["比", "bǐ", "to compare", "HSK2"],
  ["便宜", "piányi", "cheap", "HSK2"],
  ["别", "bié", "don't; other; to leave", "HSK2"],
  ["出", "chū", "to go out; to exit", "HSK2"],
  ["船", "chuán", "boat; ship", "HSK2"],
  ["次", "cì", "(measure word for occurrences); time", "HSK2"],
  ["从", "cóng", "from", "HSK2"],
  ["错", "cuò", "wrong; mistake", "HSK2"],
  ["打篮球", "dǎlánqiú", "to play basketball", "HSK2"],
  ["大家", "dàjiā", "everyone; influential family", "HSK2"],
  ["到", "dào", "to arrive; to go to", "HSK2"],
  ["得", "dé", "to get; to obtain", "HSK2"],
  ["弟弟", "dìdi", "younger brother", "HSK2"],
  ["第一", "dìyī", "first; number one", "HSK2"],
  ["房间", "fángjiān", "room", "HSK2"],
  ["服务员", "fúwùyuán", "waiter; waitress", "HSK2"],
  ["告诉", "gàosu", "to tell; to inform", "HSK2"],
  ["哥哥", "gēge", "older brother", "HSK2"],
  ["给", "gěi", "to give; for", "HSK2"],
  ["公共汽车", "gōnggòngqìchē", "bus", "HSK2"],
  ["公斤", "gōngjīn", "kilogram (kg)", "HSK2"],
  ["贵", "guì", "expensive", "HSK2"],
  ["孩子", "háizi", "child", "HSK2"],
  ["好吃", "hǎochī", "tasty; delicious", "HSK2"],
  ["号", "hào", "number; day of the month", "HSK2"],
  ["欢迎", "huānyíng", "to welcome; welcome", "HSK2"],
  ["回答", "huídá", "to reply; to answer; reply; answer", "HSK2"],
  ["鸡蛋", "jīdàn", "(chicken) egg; hen's egg", "HSK2"],
  ["件", "jiàn", "(measure word for items, clothes)", "HSK2"],
  ["教室", "jiàoshì", "classroom", "HSK2"],
  ["介绍", "jièshào", "to introduce (sb to sb); to give a presentation", "HSK2"],
  ["姐姐", "jiějie", "older sister", "HSK2"],
  ["近", "jìn", "near", "HSK2"],
  ["进", "jìn", "to enter", "HSK2"],
  ["咖啡", "kāfēi", "coffee (loanword)", "HSK2"],
  ["开始", "kāishǐ", "to begin; beginning", "HSK2"],
  ["考试", "kǎoshì", "to take an exam; exam", "HSK2"],
  ["可能", "kěnéng", "might (happen); possible", "HSK2"],
  ["课", "kè", "class; lesson", "HSK2"],
  ["快乐", "kuàilè", "happy; joyful", "HSK2"],
  ["累", "lèi", "tired", "HSK2"],
  ["离", "lí", "from; away from", "HSK2"],
  ["两", "liǎng", "two; a couple of", "HSK2"],
  ["忙", "máng", "busy", "HSK2"],
  ["每", "měi", "every", "HSK2"],
  ["妹妹", "mèimei", "younger sister; young woman", "HSK2"],
  ["男人", "nánrén", "a man; a male", "HSK2"],
  ["您", "nín", "you (polite)", "HSK2"],
  ["牛奶", "niúnǎi", "cow's milk", "HSK2"],
  ["女人", "nǚrén", "woman", "HSK2"],
  ["跑步", "pǎobù", "to run; to jog", "HSK2"],
  ["票", "piào", "ticket", "HSK2"],
  ["妻子", "qīzi", "wife", "HSK2"],
  ["千", "qiān", "thousand", "HSK2"],
  ["去年", "qùnián", "last year", "HSK2"],
  ["让", "ràng", "to let; to allow", "HSK2"],
  ["上班", "shàngbān", "to go to work; to be on duty", "HSK2"],
  ["身体", "shēntǐ", "the body; one's health", "HSK2"],
  ["生病", "shēngbìng", "to fall ill", "HSK2"],
  ["生日", "shēngrì", "birthday", "HSK2"],
  ["时间", "shíjiān", "time; period", "HSK2"],
  ["手表", "shǒubiǎo", "wristwatch", "HSK2"],
  ["送", "sòng", "to give (as a gift); to see off", "HSK2"],
  ["它", "tā", "it", "HSK2"],
  ["踢", "tī", "to kick", "HSK2"],
  ["题", "tí", "question; topic", "HSK2"],
  ["外", "wài", "outside", "HSK2"],
  ["完", "wán", "to finish", "HSK2"],
  ["玩", "wán", "to play", "HSK2"],
  ["晚上", "wǎnshang", "evening; night", "HSK2"],
  ["为", "wèi", "for; because of", "HSK2"],
  ["问", "wèn", "to ask", "HSK2"],
  ["洗", "xǐ", "to wash", "HSK2"],
  ["西瓜", "xīguā", "watermelon", "HSK2"],
  ["向", "xiàng", "towards", "HSK2"],
  ["小时", "xiǎoshí", "hour", "HSK2"],
  ["笑", "xiào", "to laugh; to smile", "HSK2"],
  ["姓", "xìng", "surname", "HSK2"],
  ["休息", "xiūxi", "rest; to rest", "HSK2"],
  ["眼睛", "yǎnjing", "eye", "HSK2"],
  ["羊肉", "yángròu", "mutton; goat meat", "HSK2"],
  ["药", "yào", "medicine", "HSK2"],
  ["要", "yào", "to want; will; to need", "HSK2"],
  ["意思", "yìsi", "idea; opinion", "HSK2"],
  ["右边", "yòubian", "right side; right, to the right", "HSK2"],
  ["鱼", "yú", "fish", "HSK2"],
  ["元", "yuán", "yuan (currency unit)", "HSK2"],
  ["远", "yuǎn", "far", "HSK2"],
  ["早上", "zǎoshang", "early morning", "HSK2"],
  ["张", "zhāng", "(measure word for flat objects); sheet", "HSK2"],
  ["丈夫", "zhàngfu", "husband", "HSK2"],
  ["找", "zhǎo", "to look for", "HSK2"],
  ["着", "zhe", "(particle indicating an action in progress)", "HSK2"],
  ["真", "zhēn", "really; truly", "HSK2"],
  ["正在", "zhèngzài", "just at (that time); right in (that place)", "HSK2"],
  ["准备", "zhǔnbèi", "preparation; to prepare", "HSK2"],
  ["自行车", "zìxíngchē", "bicycle; bike", "HSK2"],
  ["最", "zuì", "most", "HSK2"],
  ["左边", "zuǒbian", "left; the left side", "HSK2"],

  // ---- HSK3 (official 2012-standard word list, 300 words) ----
  ["老", "lǎo", "old", "HSK3"],
  ["分", "fēn", "minute; to divide", "HSK3"],
  ["站", "zhàn", "to stand; station", "HSK3"],
  ["低", "dī", "low", "HSK3"],
  ["短", "duǎn", "short", "HSK3"],
  ["旧", "jiù", "old (things)", "HSK3"],
  ["口", "kǒu", "mouth", "HSK3"],
  ["应该", "yīnggāi", "should", "HSK3"],
  ["如果", "rúguǒ", "if", "HSK3"],
  ["虽然", "suīrán", "although", "HSK3"],
  ["才", "cái", "only then", "HSK3"],
  ["特别", "tèbié", "especially", "HSK3"],
  ["一样", "yíyàng", "the same", "HSK3"],
  ["办法", "bànfǎ", "method; way", "HSK3"],
  ["关系", "guānxi", "relationship", "HSK3"],
  ["机会", "jīhuì", "opportunity", "HSK3"],
  ["历史", "lìshǐ", "history", "HSK3"],
  ["文化", "wénhuà", "culture", "HSK3"],
  ["音乐", "yīnyuè", "music", "HSK3"],
  ["银行", "yínháng", "bank", "HSK3"],
  ["超市", "chāoshì", "supermarket", "HSK3"],
  ["地铁", "dìtiě", "subway", "HSK3"],
  ["春", "chūn", "spring", "HSK3"],
  ["夏", "xià", "summer", "HSK3"],
  ["秋", "qiū", "autumn", "HSK3"],
  ["冬", "dōng", "winter", "HSK3"],
  ["城市", "chéngshì", "city", "HSK3"],
  ["国家", "guójiā", "country; nation", "HSK3"],
  ["世界", "shìjiè", "world", "HSK3"],
  ["地方", "dìfang", "place", "HSK3"],
  ["东", "dōng", "east", "HSK3"],
  ["西", "xī", "west", "HSK3"],
  ["南", "nán", "south", "HSK3"],
  ["中间", "zhōngjiān", "middle; between", "HSK3"],
  ["附近", "fùjìn", "nearby", "HSK3"],
  ["黄", "huáng", "yellow", "HSK3"],
  ["蓝", "lán", "blue", "HSK3"],
  ["绿", "lǜ", "green", "HSK3"],
  ["裤子", "kùzi", "pants", "HSK3"],
  ["鞋", "xié", "shoes", "HSK3"],
  ["洗澡", "xǐzǎo", "to bathe", "HSK3"],
  ["明白", "míngbai", "to understand", "HSK3"],
  ["忘记", "wàngjì", "to forget", "HSK3"],
  ["记得", "jìde", "to remember", "HSK3"],
  ["阿姨", "āyí", "maternal aunt; step-mother", "HSK3"],
  ["啊", "a", "(exclamatory particle)", "HSK3"],
  ["矮", "ǎi", "short (in height)", "HSK3"],
  ["爱好", "àihào", "hobby; interest", "HSK3"],
  ["安静", "ānjìng", "quiet; peaceful", "HSK3"],
  ["把", "bǎ", "(marks a following noun as a direct object); handle", "HSK3"],
  ["班", "bān", "class (in school); team", "HSK3"],
  ["搬", "bān", "to move (relocate)", "HSK3"],
  ["办公室", "bàngōngshì", "office; business premises", "HSK3"],
  ["半", "bàn", "half", "HSK3"],
  ["帮忙", "bāngmáng", "to help; to lend a hand", "HSK3"],
  ["包", "bāo", "bag; to wrap", "HSK3"],
  ["饱", "bǎo", "full (after eating)", "HSK3"],
  ["北方", "běifāng", "north; the northern part a country", "HSK3"],
  ["被", "bèi", "(passive voice marker); by; quilt", "HSK3"],
  ["鼻子", "bízi", "nose", "HSK3"],
  ["比较", "bǐjiào", "to compare; to contrast", "HSK3"],
  ["比赛", "bǐsài", "competition (sports etc); match", "HSK3"],
  ["必须", "bìxū", "to have to; must", "HSK3"],
  ["变化", "biànhuà", "(intransitive) to change; to vary; change; variation", "HSK3"],
  ["表示", "biǎoshì", "to express; to show", "HSK3"],
  ["表演", "biǎoyǎn", "play; show", "HSK3"],
  ["别人", "biéren", "other people; others; other person", "HSK3"],
  ["宾馆", "bīnguǎn", "guesthouse; lodge", "HSK3"],
  ["冰箱", "bīngxiāng", "icebox; freezer cabinet", "HSK3"],
  ["菜单", "càidān", "menu", "HSK3"],
  ["参加", "cānjiā", "to participate; to take part", "HSK3"],
  ["草", "cǎo", "grass", "HSK3"],
  ["层", "céng", "floor; story (of a building); layer", "HSK3"],
  ["差", "chà", "to lack; poor; almost", "HSK3"],
  ["衬衫", "chènshān", "shirt; blouse", "HSK3"],
  ["成绩", "chéngjì", "achievement; performance records", "HSK3"],
  ["迟到", "chídào", "to arrive late", "HSK3"],
  ["出现", "chūxiàn", "to appear; to arise", "HSK3"],
  ["除了", "chúle", "besides; apart from (... also...)", "HSK3"],
  ["厨房", "chúfáng", "kitchen", "HSK3"],
  ["词语", "cíyǔ", "word; term", "HSK3"],
  ["聪明", "cōngming", "intelligent; clever", "HSK3"],
  ["打扫", "dǎsǎo", "to clean; to sweep", "HSK3"],
  ["打算", "dǎsuàn", "to plan; to intend", "HSK3"],
  ["带", "dài", "to bring; to carry; belt", "HSK3"],
  ["担心", "dānxīn", "anxious; worried", "HSK3"],
  ["蛋糕", "dàngāo", "cake", "HSK3"],
  ["当然", "dāngrán", "only natural; as it should be", "HSK3"],
  ["地", "dì", "land; ground; place", "HSK3"],
  ["地图", "dìtú", "map", "HSK3"],
  ["灯", "dēng", "lamp; light", "HSK3"],
  ["电梯", "diàntī", "elevator; escalator", "HSK3"],
  ["电子", "diànzǐ", "electronic; electron (particle physics)", "HSK3"],
  ["动物", "dòngwù", "animal", "HSK3"],
  ["段", "duàn", "(measure word for a section, paragraph)", "HSK3"],
  ["锻炼", "duànliàn", "to toughen; to temper", "HSK3"],
  ["多么", "duōme", "how (wonderful etc); what (a great idea etc)", "HSK3"],
  ["饿", "è", "hungry", "HSK3"],
  ["而且", "érqiě", "(not only ...) but also; moreover", "HSK3"],
  ["耳朵", "ěrduo", "ear; handle (on a cup)", "HSK3"],
  ["发烧", "fāshāo", "to have a high temperature (from illness); to have a fever", "HSK3"],
  ["发现", "fāxiàn", "to discover; to find", "HSK3"],
  ["方便", "fāngbiàn", "convenient; suitable", "HSK3"],
  ["放", "fàng", "to put; to place", "HSK3"],
  ["放心", "fàngxīn", "to feel relieved; to feel reassured", "HSK3"],
  ["复习", "fùxí", "to review; revision", "HSK3"],
  ["敢", "gǎn", "to dare", "HSK3"],
  ["感冒", "gǎnmào", "to catch cold; (common) cold", "HSK3"],
  ["干净", "gānjìng", "clean; neat", "HSK3"],
  ["刚才", "gāngcái", "just now; a moment ago", "HSK3"],
  ["根据", "gēnjù", "according to; based on", "HSK3"],
  ["跟", "gēn", "with; to follow", "HSK3"],
  ["更", "gèng", "even more", "HSK3"],
  ["公园", "gōngyuán", "park (for public recreation)", "HSK3"],
  ["故事", "gùshi", "story", "HSK3"],
  ["刮", "guā", "to blow (of wind); to scrape", "HSK3"],
  ["关", "guān", "to close; to turn off", "HSK3"],
  ["关心", "guānxīn", "to be concerned about; to care about", "HSK3"],
  ["关于", "guānyú", "pertaining to; concerning", "HSK3"],
  ["果汁", "guǒzhī", "fruit juice", "HSK3"],
  ["过去", "guòqù", "(in the) past; former", "HSK3"],
  ["还是", "háishi", "still (as before); had better", "HSK3"],
  ["害怕", "hàipà", "to be afraid; to be scared", "HSK3"],
  ["河", "hé", "river", "HSK3"],
  ["黑板", "hēibǎn", "blackboard", "HSK3"],
  ["护照", "hùzhào", "passport", "HSK3"],
  ["花", "huā", "flower; to spend (money, time)", "HSK3"],
  ["花园", "huāyuán", "garden", "HSK3"],
  ["画", "huà", "to draw; picture", "HSK3"],
  ["坏", "huài", "bad; broken", "HSK3"],
  ["环境", "huánjìng", "environment; circumstances", "HSK3"],
  ["换", "huàn", "to exchange; to change", "HSK3"],
  ["会议", "huìyì", "meeting; conference", "HSK3"],
  ["或者", "huòzhě", "or; possibly; maybe; perhaps", "HSK3"],
  ["极", "jí", "extremely", "HSK3"],
  ["几乎", "jīhū", "almost; nearly; practically", "HSK3"],
  ["季节", "jìjié", "time; season", "HSK3"],
  ["检查", "jiǎnchá", "inspection; to examine", "HSK3"],
  ["简单", "jiǎndān", "simple; not complicated", "HSK3"],
  ["见面", "jiànmiàn", "to meet; to see each other", "HSK3"],
  ["健康", "jiànkāng", "health; healthy", "HSK3"],
  ["讲", "jiǎng", "to speak; to explain", "HSK3"],
  ["角", "jiǎo", "corner; angle", "HSK3"],
  ["脚", "jiǎo", "foot", "HSK3"],
  ["教", "jiāo", "to teach", "HSK3"],
  ["接", "jiē", "to receive; to pick (someone) up", "HSK3"],
  ["街道", "jiēdào", "street; subdistrict", "HSK3"],
  ["节目", "jiémù", "program; item (on a program)", "HSK3"],
  ["节日", "jiérì", "holiday; festival", "HSK3"],
  ["结婚", "jiéhūn", "to marry; to get married", "HSK3"],
  ["结束", "jiéshù", "termination; to finish", "HSK3"],
  ["解决", "jiějué", "to solve; to resolve", "HSK3"],
  ["借", "jiè", "to borrow; to lend", "HSK3"],
  ["经常", "jīngcháng", "often; frequently", "HSK3"],
  ["经过", "jīngguò", "to pass; to go through", "HSK3"],
  ["经理", "jīnglǐ", "manager; director", "HSK3"],
  ["久", "jiǔ", "(for) a long time", "HSK3"],
  ["举行", "jǔxíng", "to hold (a meeting, ceremony etc)", "HSK3"],
  ["句子", "jùzi", "sentence", "HSK3"],
  ["决定", "juédìng", "to decide (to do something); to resolve", "HSK3"],
  ["可爱", "kěài", "adorable; cute", "HSK3"],
  ["渴", "kě", "thirsty", "HSK3"],
  ["刻", "kè", "quarter hour; moment", "HSK3"],
  ["客人", "kèrén", "visitor; guest", "HSK3"],
  ["空调", "kōngtiáo", "air conditioning", "HSK3"],
  ["哭", "kū", "to cry", "HSK3"],
  ["筷子", "kuàizi", "chopsticks", "HSK3"],
  ["了解", "liǎojiě", "to understand; to realize", "HSK3"],
  ["离开", "líkāi", "to depart; to leave", "HSK3"],
  ["礼物", "lǐwù", "gift; present", "HSK3"],
  ["脸", "liǎn", "face", "HSK3"],
  ["练习", "liànxí", "to practice; exercise", "HSK3"],
  ["辆", "liàng", "(measure word for vehicles)", "HSK3"],
  ["邻居", "línjū", "neighbor; next door", "HSK3"],
  ["楼", "lóu", "building; floor (of a building)", "HSK3"],
  ["马", "mǎ", "horse", "HSK3"],
  ["马上", "mǎshàng", "at once; right away", "HSK3"],
  ["满意", "mǎnyì", "satisfied; pleased", "HSK3"],
  ["帽子", "màozi", "hat; cap", "HSK3"],
  ["米", "mǐ", "rice; meter", "HSK3"],
  ["面包", "miànbāo", "bread", "HSK3"],
  ["面条", "miàntiáo", "noodles", "HSK3"],
  ["拿", "ná", "to take; to hold", "HSK3"],
  ["奶奶", "nǎinai", "grandma (paternal)", "HSK3"],
  ["难", "nán", "difficult", "HSK3"],
  ["难过", "nánguò", "to feel sad; to feel unwell", "HSK3"],
  ["年级", "niánjí", "grade; year (in school, college etc)", "HSK3"],
  ["年轻", "niánqīng", "young", "HSK3"],
  ["鸟", "niǎo", "bird", "HSK3"],
  ["努力", "nǔlì", "to work hard; to strive", "HSK3"],
  ["爬山", "páshān", "to climb a mountain; to mountaineer", "HSK3"],
  ["盘子", "pánzi", "tray; plate", "HSK3"],
  ["胖", "pàng", "fat; plump", "HSK3"],
  ["啤酒", "píjiǔ", "beer (loanword)", "HSK3"],
  ["葡萄", "pútao", "grape", "HSK3"],
  ["普通话", "pǔtōnghuà", "Mandarin Chinese", "HSK3"],
  ["其实", "qíshí", "actually; in fact; really", "HSK3"],
  ["其他", "qítā", "other; (sth or sb) else", "HSK3"],
  ["奇怪", "qíguài", "strange; odd", "HSK3"],
  ["骑", "qí", "to ride", "HSK3"],
  ["铅笔", "qiānbǐ", "(lead) pencil", "HSK3"],
  ["清楚", "qīngchu", "clear; distinct", "HSK3"],
  ["裙子", "qúnzi", "skirt", "HSK3"],
  ["然后", "ránhòu", "then; after that; afterwards", "HSK3"],
  ["热情", "rèqíng", "cordial; enthusiastic", "HSK3"],
  ["认为", "rènwéi", "to believe; to think; to consider; to feel", "HSK3"],
  ["认真", "rènzhēn", "conscientious; earnest", "HSK3"],
  ["容易", "róngyì", "easy; straightforward; likely; liable to; apt to", "HSK3"],
  ["伞", "sǎn", "umbrella", "HSK3"],
  ["上网", "shàngwǎng", "to go online; to connect to the Internet", "HSK3"],
  ["生气", "shēngqì", "to get angry; to take offense", "HSK3"],
  ["声音", "shēngyīn", "voice; sound", "HSK3"],
  ["使", "shǐ", "to make; to cause; to use", "HSK3"],
  ["瘦", "shòu", "thin; skinny", "HSK3"],
  ["叔叔", "shūshu", "father's younger brother; uncle", "HSK3"],
  ["舒服", "shūfu", "comfortable; feeling well", "HSK3"],
  ["树", "shù", "tree", "HSK3"],
  ["数学", "shùxué", "mathematics; mathematical", "HSK3"],
  ["刷", "shuā", "to brush", "HSK3"],
  ["双", "shuāng", "pair; (measure word for a pair)", "HSK3"],
  ["水平", "shuǐpíng", "level (of achievement etc); standard", "HSK3"],
  ["司机", "sījī", "chauffeur; driver", "HSK3"],
  ["太阳", "tàiyang", "sun; abbr. for 太阳穴", "HSK3"],
  ["糖", "táng", "sugar; candy", "HSK3"],
  ["疼", "téng", "to hurt; sore", "HSK3"],
  ["提高", "tígāo", "to raise; to increase", "HSK3"],
  ["体育", "tǐyù", "sports; physical education", "HSK3"],
  ["甜", "tián", "sweet", "HSK3"],
  ["条", "tiáo", "(measure word for long thin things)", "HSK3"],
  ["同事", "tóngshì", "colleague; co-worker", "HSK3"],
  ["同意", "tóngyì", "to agree; to consent", "HSK3"],
  ["头发", "tóufa", "hair (on the head)", "HSK3"],
  ["突然", "tūrán", "sudden; abrupt; unexpected", "HSK3"],
  ["图书馆", "túshūguǎn", "library", "HSK3"],
  ["腿", "tuǐ", "leg", "HSK3"],
  ["完成", "wánchéng", "to complete; to accomplish", "HSK3"],
  ["碗", "wǎn", "bowl", "HSK3"],
  ["万", "wàn", "ten thousand", "HSK3"],
  ["为了", "wèile", "for; for the purpose of; in order to", "HSK3"],
  ["为什么", "wèishénme", "why?; for what reason?", "HSK3"],
  ["位", "wèi", "(polite measure word for people)", "HSK3"],
  ["习惯", "xíguàn", "habit; custom", "HSK3"],
  ["洗手间", "xǐshǒujiān", "toilet; lavatory", "HSK3"],
  ["先", "xiān", "first", "HSK3"],
  ["相同", "xiāngtóng", "identical; same", "HSK3"],
  ["相信", "xiāngxìn", "to believe", "HSK3"],
  ["香蕉", "xiāngjiāo", "banana", "HSK3"],
  ["像", "xiàng", "to resemble; to be like", "HSK3"],
  ["小心", "xiǎoxīn", "to be careful; to take care", "HSK3"],
  ["校长", "xiàozhǎng", "(college, university) president; headmaster", "HSK3"],
  ["新闻", "xīnwén", "news", "HSK3"],
  ["新鲜", "xīnxiān", "fresh (experience, food etc); freshness", "HSK3"],
  ["信", "xìn", "letter (mail)", "HSK3"],
  ["行李箱", "xínglixiāng", "suitcase; baggage compartment", "HSK3"],
  ["兴趣", "xìngqù", "interest", "HSK3"],
  ["熊猫", "xióngmāo", "panda", "HSK3"],
  ["需要", "xūyào", "to need; to want; to demand; to require; needs", "HSK3"],
  ["选择", "xuǎnzé", "to select; to pick", "HSK3"],
  ["眼镜", "yǎnjìng", "spectacles; eyeglasses", "HSK3"],
  ["要求", "yāoqiú", "to request; to require", "HSK3"],
  ["爷爷", "yéye", "(coll.) father's father; paternal grandfather", "HSK3"],
  ["一般", "yībān", "same; ordinary", "HSK3"],
  ["一边", "yībiān", "one side; either side", "HSK3"],
  ["一定", "yīdìng", "surely; certainly", "HSK3"],
  ["一共", "yīgòng", "altogether", "HSK3"],
  ["一会儿", "yīhuìr", "a moment; a while", "HSK3"],
  ["一直", "yīzhí", "always; continuously", "HSK3"],
  ["以后", "yǐhòu", "after; later", "HSK3"],
  ["以前", "yǐqián", "before; formerly", "HSK3"],
  ["以为", "yǐwéi", "to think (mistakenly)", "HSK3"],
  ["影响", "yǐngxiǎng", "influence; effect", "HSK3"],
  ["用", "yòng", "to use", "HSK3"],
  ["游戏", "yóuxì", "game; to play", "HSK3"],
  ["有名", "yǒumíng", "famous; well-known", "HSK3"],
  ["又", "yòu", "again; also", "HSK3"],
  ["遇到", "yùdào", "to meet; to run into; to come across", "HSK3"],
  ["愿意", "yuànyì", "to wish; to want", "HSK3"],
  ["月亮", "yuèliang", "the moon", "HSK3"],
  ["越", "yuè", "to exceed; the more...", "HSK3"],
  ["云", "yún", "cloud", "HSK3"],
  ["照顾", "zhàogu", "to take care of; to show consideration", "HSK3"],
  ["照片", "zhàopiàn", "photograph; picture", "HSK3"],
  ["照相机", "zhàoxiàngjī", "camera", "HSK3"],
  ["着急", "zháojí", "to worry; to be anxious", "HSK3"],
  ["只", "zhǐ", "only", "HSK3"],
  ["终于", "zhōngyú", "at last; in the end", "HSK3"],
  ["种", "zhǒng", "kind; type; seed", "HSK3"],
  ["重要", "zhòngyào", "important; significant", "HSK3"],
  ["周末", "zhōumò", "weekend", "HSK3"],
  ["主要", "zhǔyào", "main; principal", "HSK3"],
  ["注意", "zhùyì", "to take note of; to pay attention to", "HSK3"],
  ["祝", "zhù", "to wish (someone well)", "HSK3"],
  ["字典", "zìdiǎn", "dictionary", "HSK3"],
  ["自己", "zìjǐ", "oneself; one's own", "HSK3"],
  ["总是", "zǒngshì", "always", "HSK3"],
  ["最近", "zuìjìn", "recently; soon", "HSK3"],
  ["作业", "zuòyè", "school assignment; homework", "HSK3"],
  ["作用", "zuòyòng", "to act on; to affect", "HSK3"],

  // ---- Beyond HSK3 (not in the official HSK1-3 lists) ----
  ["不同", "bùtóng", "different", "HSK4+ (extra)"],
  ["经验", "jīngyàn", "experience", "HSK4+ (extra)"],
  ["火车", "huǒchē", "train", "HSK4+ (extra)"],
  ["风", "fēng", "wind", "HSK4+ (extra)"],
  ["北", "běi", "north", "HSK4+ (extra)"],
  ["里面", "lǐmiàn", "inside", "HSK4+ (extra)"],
  ["外面", "wàimiàn", "outside", "HSK4+ (extra)"],
  ["篮球", "lánqiú", "basketball", "HSK4+ (extra)"],
  ["足球", "zúqiú", "soccer", "HSK4+ (extra)"],
  ["照相", "zhàoxiàng", "to take a photo", "HSK4+ (extra)"],

  // ---- Geography: countries, cities, continents ----
  ["中国", "Zhōngguó", "China", "Geography"],
  ["美国", "Měiguó", "United States", "Geography"],
  ["英国", "Yīngguó", "United Kingdom", "Geography"],
  ["法国", "Fàguó", "France", "Geography"],
  ["德国", "Déguó", "Germany", "Geography"],
  ["日本", "Rìběn", "Japan", "Geography"],
  ["韩国", "Hánguó", "South Korea", "Geography"],
  ["俄罗斯", "Éluósī", "Russia", "Geography"],
  ["加拿大", "Jiānádà", "Canada", "Geography"],
  ["澳大利亚", "Àodàlìyà", "Australia", "Geography"],
  ["意大利", "Yìdàlì", "Italy", "Geography"],
  ["西班牙", "Xībānyá", "Spain", "Geography"],
  ["印度", "Yìndù", "India", "Geography"],
  ["巴西", "Bāxī", "Brazil", "Geography"],
  ["墨西哥", "Mòxīgē", "Mexico", "Geography"],
  ["埃及", "Āijí", "Egypt", "Geography"],
  ["泰国", "Tàiguó", "Thailand", "Geography"],
  ["越南", "Yuènán", "Vietnam", "Geography"],
  ["新加坡", "Xīnjiāpō", "Singapore", "Geography"],
  ["瑞士", "Ruìshì", "Switzerland", "Geography"],
  ["北京", "Běijīng", "Beijing", "Geography"],
  ["上海", "Shànghǎi", "Shanghai", "Geography"],
  ["广州", "Guǎngzhōu", "Guangzhou", "Geography"],
  ["深圳", "Shēnzhèn", "Shenzhen", "Geography"],
  ["香港", "Xiānggǎng", "Hong Kong", "Geography"],
  ["台北", "Táiběi", "Taipei", "Geography"],
  ["纽约", "Niǔyuē", "New York", "Geography"],
  ["伦敦", "Lúndūn", "London", "Geography"],
  ["巴黎", "Bālí", "Paris", "Geography"],
  ["东京", "Dōngjīng", "Tokyo", "Geography"],
  ["首尔", "Shǒu'ěr", "Seoul", "Geography"],
  ["悉尼", "Xīní", "Sydney", "Geography"],
  ["莫斯科", "Mòsīkē", "Moscow", "Geography"],
  ["亚洲", "Yàzhōu", "Asia", "Geography"],
  ["欧洲", "Ōuzhōu", "Europe", "Geography"],
  ["非洲", "Fēizhōu", "Africa", "Geography"],
  ["北美洲", "Běiměizhōu", "North America", "Geography"],
  ["南美洲", "Nánměizhōu", "South America", "Geography"],
  ["大洋洲", "Dàyángzhōu", "Oceania", "Geography"],

  // ---- Common four-character idioms (成语) ----
  ["马马虎虎", "mǎmǎhūhū", "careless; so-so", "Idiom"],
  ["半途而废", "bàntú'érfèi", "to give up halfway", "Idiom"],
  ["画蛇添足", "huàshétiānzú", "to ruin by overdoing it (lit. draw a snake, add feet)", "Idiom"],
  ["守株待兔", "shǒuzhūdàitù", "to wait idly for a windfall (lit. guard a stump, wait for a rabbit)", "Idiom"],
  ["一举两得", "yìjǔliǎngdé", "to kill two birds with one stone", "Idiom"],
  ["入乡随俗", "rùxiāngsuísú", "when in Rome, do as the Romans do", "Idiom"],
  ["狼吞虎咽", "lángtūnhǔyàn", "to wolf down food", "Idiom"],
  ["对牛弹琴", "duìniútánqín", "to waste words on the wrong audience (lit. play lute to a cow)", "Idiom"],
  ["自相矛盾", "zìxiāngmáodùn", "self-contradictory", "Idiom"],
  ["画龙点睛", "huàlóngdiǎnjīng", "to add the crucial finishing touch", "Idiom"],
  ["亡羊补牢", "wángyángbǔláo", "better late than never (lit. mend the pen after the sheep is lost)", "Idiom"],
  ["拔苗助长", "bámiáozhùzhǎng", "to ruin things by forcing progress", "Idiom"],
  ["井底之蛙", "jǐngdǐzhīwā", "a person with a narrow view (lit. frog at the bottom of a well)", "Idiom"],
  ["掩耳盗铃", "yǎn'ěrdàolíng", "to deceive only oneself", "Idiom"],
  ["刻舟求剑", "kèzhōuqiújiàn", "rigidly stuck to an outdated method", "Idiom"],
  ["塞翁失马", "sàiwēngshīmǎ", "a blessing in disguise", "Idiom"],
  ["胸有成竹", "xiōngyǒuchéngzhú", "to have a well-thought-out plan already in mind", "Idiom"],
  ["纸上谈兵", "zhǐshàngtánbīng", "armchair strategy; all theory, no practice", "Idiom"],
  ["锦上添花", "jǐnshàngtiānhuā", "to make something already good even better", "Idiom"],
  ["雪中送炭", "xuězhōngsòngtàn", "to help someone in urgent need", "Idiom"],
  ["一心一意", "yìxīnyíyì", "wholeheartedly", "Idiom"],
  ["半信半疑", "bànxìnbànyí", "half-believing, half-doubting", "Idiom"],
  ["恍然大悟", "huǎngrándàwù", "to suddenly realize", "Idiom"],
  ["不可思议", "bùkěsīyì", "inconceivable; unimaginable", "Idiom"],
  ["心想事成", "xīnxiǎngshìchéng", "may your wishes come true", "Idiom"],
  ["一帆风顺", "yìfānfēngshùn", "smooth sailing", "Idiom"],
  ["万事如意", "wànshìrúyì", "may everything go as you wish", "Idiom"],
  ["人山人海", "rénshānrénhǎi", "a huge crowd (lit. people mountain, people sea)", "Idiom"],
  ["乱七八糟", "luànqībāzāo", "in a total mess", "Idiom"],
  ["知足常乐", "zhīzúchánglè", "content with what one has is always happy", "Idiom"],
];
